"""name complex

Revision ID: 7153e26887f3
Revises: 30ff9e9288a0
Create Date: 2024-03-25 22:07:29.404790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7153e26887f3'
down_revision: Union[str, None] = '30ff9e9288a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexes', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_constraint('uq_complexes_id', 'complexes', type_='unique')
    op.create_unique_constraint(op.f('uq_complexes_id'), 'complexes', ['id', 'competition_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_complexes_id'), 'complexes', type_='unique')
    op.create_unique_constraint('uq_complexes_id', 'complexes', ['id', 'competition_id'])
    op.drop_column('complexes', 'name')
    # ### end Alembic commands ###
