"""default qualifying status

Revision ID: 30ff9e9288a0
Revises: b8b43c9d4838
Create Date: 2024-03-25 20:48:25.656492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ff9e9288a0'
down_revision: Union[str, None] = 'b8b43c9d4838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'qualifying_videos',
        'qualifier_status',
        server_default=sa.schema.DefaultClause('unqualified')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
